env:
  global:
  - secure: s8DdaxdWVR3qRBxfxO6UjugB1dWlEnv9KhF1ZUHDhWziPtoecKjCXnJYSB6EOddTPoJXtOdTVW9ThGGCvKQ+vYdGNce+PCWglruANO/lEz/82HWPZkTKbw4WyoDo5GqlFCu1C3gY9dA58ClpGDlX5BNQA81JCJrWKUdR2J0/WW9USPKHxDLGISYKt28nwVjywR8uDnysBJkmmS+53Ge2MSzmOLuEZeysq7iCD6xssPL5UDDb/itNOc4OkvRGtvTnLrMF4c7naFRfbhc7NR1MxKz+eu2DgM9SAnJrh1jnYXWu/1EG8VKQOYR23OwjxSurSRjJxInGZdrSGUB8R38Z35Ndq7RHKRAZvwIPkZqDFCUQ/hkAJlu/4cbz8KPHJMOV0SOFpCztnFCQY619KXn0S0Tos38KthVu2nNSMJu1e1GuQK1dhM+Uh3MCrSChyPmK75IKbM7Jj5OKRqKO4uSnsut3RK91RYF3oB3HdLkznTLYBLnyEWK6Zh56lhoZiJMd/WCL24/U5Pne6VwLDBjaeOH9lEjD6oaUSIDyowVAOte4qVg7WW7OXx2fkK9ySd4X0P5C5JLtWsZ8O+va9LkIxPPCdck3HV+k1EU0tHrLAAkpwO3D9StRdkc7cX+z13aFOZQyKef1wbKyNCYrq6E3SGvlI011+0vN2ZiGKKusGcs=
  - secure: JuSus/BqBJ2RTj7oJ3tn6dfFqnNWmWdM6/+PBId8YT52fUJTQp0eLmYbqZhq04OFvCKLgzeiObggfFZk5VOXAB/bfhlQEKSprso6C0WxKzFnftr085rcr5mW2ux+RSWTeE9KT1bpsjtpSrQTOniQhPGD6u704DdIzKuOnSngU8TXRAHFujXtUA0SHU8Oft8OpysaTDVWbFehBemg6BeOssklw2LrScGT3AWm8+qNdyAV+ynko4s8CzdOJqueCNWnkYFQyNtWN67uasveg3j+zgOfstjgyYSEoYh6deCNy8BjmWzX2tUkpzxh7h4w/VlyVjvyMG524UdMDmFZNNo7CMn1/qla6zjli3xDV/kk2Dfzj1JCn2WsesOY8+p4bdYoUU4lR0PuYraEuBAOCiVb3V7VLzU5FyV3clY8+MwifVHvNLxUbyD2ygZfPrS8LQJ/7jJSPeEARUIngvNkY9L8Jr6olw3Xg7DoDHLWAFBMtBi/sZG3CvXDyeIUX8rkh4hY6QlnO/xrql5KxDupsAwqj+rMdhzYeCnyRY6HvqBIoIrpi47uPGutxiIFgjrzwr28eL+XrrkwHfbM+pFDUITdWjm79/EyEPgGsEMM8IxXcpSGNmMDDhpHu1oZE4L3gdKli6hdS5fo6CEDV3x1nvk/SsY52WhEWIT/RwQPl4qL3YQ=
  - coverity_scan_run_condition='"$TRAVIS_OS_NAME" != osx -a "$BUILD_TYPE" = Release'
  - coverity_scan_script_test_mode=false
  - secure: tvFQn4BjO/DG0yE5NEdZsmY73qsxhN5CsXl+C4GkCzz8KgtOGyVFij5R18+IP3X44CKOz54dLy9pE3lCY2v9wvvLnnv1hV3kH2EvV5Ccv2zw8jozz7OpxK2GMSoqPvHK/FAEo3mbuwhnOS2fEV3+hWSF9/piwSAmFhnjH7VHZnnx8yVfpzEl0Oq4JLM1fEx400Z+Glvn9uDfjY8cvzRVp8HqHTuPNNRLmNvGPAYqstpKAxEh6Tml6eUrCxbndbcvtTt7vlshW9OuU5LVh2Y63ftZpsKCWfpu5K4MfgD4oLineo+2zz3jfv/Hs8vTVLzRQph6OkxLiZBqUgUyoZzZ/r4bMQbbS6wmbWwZOaIQyjFRr68FZ/yW4JJ/KkUhMB3LA7it2rNhhI6+jTQqvLO+VAucuUmFJ0xIsbULBTo7cyL7X40rDLFxhXNLTjcqPT1nUzKCrmFxrDh7utegggN0UtXVAWl6KN8f003TVlunM+BrB8r08kX/JU0modFzXS0sMDF/tuzMd9dd/R4CtoHAuP20J7LZ81EA8IbKJ5j6dsc8l+Ti5/LwLrEtxXnD6MSSNDoSZszeyLA78+zGzKLNNvHGdnHTFgFd3Q/gVYJgH6AWAVCJeSnwXbI78azIFohPwsT/JsJS092Ck6rgRKpbZNNmOVfpn6WsXoQBrLpcg0A=
  # start artifacts
  - ARTIFACTS_BUCKET=osirose-builds
  - secure: "tDTFSzBd6ASR8BM/pZMLMQy1jjlbxA81WaLfZ70OgTZE6KZ+X+mSdu/i5SyXzhdZSl62tVDo2jIjGupGLtzWjMtRJiN2zNHscYS+V4BbSfk97zKXs+fH96aDlGJBIqJSxT3aRqgvTCLFXzEWyZEQxzYX7u9I5P0ftMBOalkxfcU1JrBerJBdsXLFuGjKfyGfCOzvRBCjzpAhKHTsD4ecJyqqTk3XqDqE4P+8ibJXw0fWj6D0K2XTNq4krol+Vmcw2qZEGp3gVAy6blOM1ggopFRr/gTZjyA6Q/twnS07DH7w1v2RnCMjc12rTlR8usVrHYo73FUO47PMuWy/UhOhziuJy9Zu6GxcenRS/JmVYVY3cDcuczkrHX4JIn/qtwNROd8vhos+rOMFv04KsZYOkILrJmSmrwELldTw1/VkKMuk7rjcS+lcGbm2K+XZ9xUXefNGNnYbWlpQ6v8anAgOFU0/eOY3y2PknhH/2tUxX+hHq1AFMv63cGkSoRLPSXKz8gdKKN1dEIb8/ZLrz5glvv6rsLRqfvO6K3U1jyM5Sb2YCpIRd2x8CEv09QwVHWVjXdmBSVURdfY3p41G16wvMT3GCH7/VCJ6rGz1WmFzMEDX2ua5P+SFXagL0iBZNmF1HWVxkpwE1MGPkq/WlpSw//cY+2PNBktDjClluzE3w9s="
  - secure: "CgXInxIv08nvVBQY9UgP9ZeBMlDyuQ9wr0DmoB61UGMGNaJps11Shuikz0tDcJxqFsSapJPkXc03B6rK7Bhckdz3MKYp0RLNsEv0984QkKiseYnqFc6h6qJGV2AgsbHLBKZoqxVxeDV2biKvYqDkG3ylTSSaL7+eMvTguc2aK9zUhcFKoBdsRBECTdte2Nd/GVUIJIuUaFMncuTscZLR5VwNaN8xf6BTG5oitKbBje304/soMgHL9WdGuzeBT42QtE8yJ82SmlPvV/dAjGaSwLENmehpc3XIlaevrJg4Ptti8XBazjwvCR9bF5HVnP5uADqmLcznl1PQXDLjNeVryLjnFvAf4wveLxHeW13olMnZsgV84ABWEHTcUuz4z5KM+BKvLGjQB3R9msVr2YKn0KJfqeCPSdnctKAgKlYyRFKOIuohuHsVu+PJzq6NOFWs6c3IrEE+YgqSXhpgFcARt/Z1BTfVm9sAlHEY5I9Hlzxfl+F9HvjvQXtzhwt3fMB6dCeQfnGp/k660Q4wpo7zWHPc7o2OskeZwrTKzaSovFYXltGRQxDKOPZEjA1aLpK8Dnk46x+p9Kd+ClsV+WeOOG+u3xjR90NIjhOziurtMgMy/m/XluIvbMDCChZF8ecvo5+qEWeB9fAp3dSrkn4xInbTG+747P3hL2FxRLflwdo="
  # end artifacts
  - PROOT=$TRAVIS_BUILD_DIR
  - SUITE=tests
services:
- mysql

branches:
  except:
  - coverity_scan

matrix:
  include:
  - env: g++-5 BUILD_TYPE=Release
    sudo: required
    language: cpp
    addons:
#      artifacts:
#        paths:
#        - ${PROOT}/${TRAVIS_OS_NAME}-${TRAVIS_JOB_NUMBER}.tar.gz
      apt:
        sources:
        - ubuntu-toolchain-r-test
        - extras-precise
        - boost-latest
        - kalakris-cmake
        packages:
        - cmake
        - lcov
        - libboost-dev
        - perl
        - gcc-5
        - g++-5
    cache:
      directories:
      - "./protobuf"
    before_install:
    - export GCOV_PATH=/usr/bin/gcov-5
    - export LCOV_PATH=$HOME/usr/bin/lcov
    - export GENHTML_PATH=$HOME/usr/bin/genhtml
    - export PREFIX=$HOME
    - export CXX="/usr/bin/g++-5" CC="/usr/bin/gcc-5";
    - bash ./ci/.travis.install-mysql-5.7.sh
    - "./ci/before_install.sh"
    install:
    - "./ci/install.sh"
    before_script:
    - mysql --user="root" -e 'create database osirose;';
    - mysql --user="root" --database="osirose" --password="" < "./Database/osirose.sql";
    - mkdir build && cd build;
    - mkdir logs;
    script:
    - "../ci/script.sh;"
  - env: g++-6 BUILD_TYPE=Debug
    sudo: required
    language: cpp
    addons:
#      artifacts:
#        paths:
#        - ${PROOT}/${TRAVIS_OS_NAME}-${TRAVIS_JOB_NUMBER}.tar.gz
      apt:
        sources:
        - ubuntu-toolchain-r-test
        - extras-precise
        - boost-latest
        - kalakris-cmake
        packages:
        - cmake
        - lcov
        - libboost-dev
        - perl
        - gcc-6
        - g++-6
    cache:
      directories:
      - "./protobuf"
    before_install:
    - export GCOV_PATH=/usr/bin/gcov-6
    - export LCOV_PATH=$HOME/usr/bin/lcov
    - export GENHTML_PATH=$HOME/usr/bin/genhtml
    - export PREFIX=$HOME
    - export CXX="/usr/bin/g++-6" CC="/usr/bin/gcc-6";
    - bash ./ci/.travis.install-mysql-5.7.sh
    - "./ci/before_install.sh"
    install:
    - "./ci/install.sh"
    before_script:
    - mysql --user="root" -e 'create database osirose;';
    - mysql --user="root" --database="osirose" --password="" < "./Database/osirose.sql";
    - mkdir build && cd build;
    - mkdir logs;
    script:
    - "../ci/script.sh;"
  - env: g++-6 BUILD_TYPE=Release
    sudo: required
    language: cpp
    addons:
#      artifacts:
#        paths:
#        - ${PROOT}/${TRAVIS_OS_NAME}-${TRAVIS_JOB_NUMBER}.tar.gz
      apt:
        sources:
        - ubuntu-toolchain-r-test
        - extras-precise
        - boost-latest
        - kalakris-cmake
        packages:
        - cmake
        - lcov
        - libboost-dev
        - perl
        - gcc-6
        - g++-6
    cache:
      directories:
      - "./protobuf"
    before_install:
    - export SUITE=none
    - export GCOV_PATH=/usr/bin/gcov-6
    - export LCOV_PATH=$HOME/usr/bin/lcov
    - export GENHTML_PATH=$HOME/usr/bin/genhtml
    - export PREFIX=$HOME
    - export CXX="/usr/bin/g++-6" CC="/usr/bin/gcc-6";
    - bash ./ci/.travis.install-mysql-5.7.sh
    - "./ci/before_install.sh"
    install:
    - "./ci/install.sh"
    before_script:
    - mysql --user="root" -e 'create database osirose;';
    - mysql --user="root" --database="osirose" --password="" < "./Database/osirose.sql";
    - mkdir build && cd build;
    - mkdir logs;
    script:
    - "../ci/script.sh;"
  - env: clang-3.7 LIBCXX=1 BUILD_TYPE=Debug
    sudo: required
    language: cpp
    addons:
#      artifacts:
#        paths:
#        - ${PROOT}/${TRAVIS_OS_NAME}-${TRAVIS_JOB_NUMBER}.tar.gz
      apt:
        sources:
        - ubuntu-toolchain-r-test
        - extras-precise
        - boost-latest
        - kalakris-cmake
        - llvm-toolchain-precise-3.7
        packages:
        - cmake
        - lcov
        - libboost-dev
        - perl
        - llvm-3.7
        - llvm-3.7-dev
        - llvm-runtime
        - clang-3.7
        - libstdc++5
    cache:
      directories:
      - "./protobuf"
      - llvm-3.7.0
    before_install:
    - export GCOV_PATH=${PROOT}/ci/llvm-gcov.sh
    - export LCOV_PATH=$HOME/usr/bin/lcov
    - export GENHTML_PATH=$HOME/usr/bin/genhtml
    - export PREFIX=$HOME
    - export CXX="/usr/bin/clang++-3.7" CC="/usr/bin/clang-3.7";
    - bash ./ci/.travis.install-mysql-5.7.sh
    - "./ci/before_install.sh"
    install:
    - "./ci/install.sh"
    before_script:
    - mysql --user="root" -e 'create database osirose;';
    - mysql --user="root" --database="osirose" --password="" < "./Database/osirose.sql";
    - mkdir build && cd build;
    - mkdir logs;
    script:
    - "../ci/script.sh;"
  - env: clang-3.7 LIBCXX=1 BUILD_TYPE=Release
    sudo: required
    language: cpp
    addons:
#      artifacts:
#        paths:
#        - ${PROOT}/${TRAVIS_OS_NAME}-${TRAVIS_JOB_NUMBER}.tar.gz
      apt:
        sources:
        - ubuntu-toolchain-r-test
        - extras-precise
        - boost-latest
        - kalakris-cmake
        - llvm-toolchain-precise-3.7
        packages:
        - cmake
        - lcov
        - libboost-dev
        - perl
        - llvm-3.7
        - llvm-3.7-dev
        - llvm-runtime
        - clang-3.7
        - libstdc++5
    cache:
      directories:
      - "./protobuf"
      - llvm-3.7.0
    before_install:
    - export GCOV_PATH=${PROOT}/ci/llvm-gcov.sh
    - export LCOV_PATH=$HOME/usr/bin/lcov
    - export GENHTML_PATH=$HOME/usr/bin/genhtml
    - export PREFIX=$HOME
    - export CXX="/usr/bin/clang++-3.7" CC="/usr/bin/clang-3.7";
    - bash ./ci/.travis.install-mysql-5.7.sh
    - "./ci/before_install.sh"
    install:
    - "./ci/install.sh"
    before_script:
    - mysql --user="root" -e 'create database osirose;';
    - mysql --user="root" --database="osirose" --password="" < "./Database/osirose.sql";
    - mkdir build && cd build;
    - mkdir logs;
    script:
    - "../ci/script.sh;"
    
  - env: g++-6 coverity_scan BUILD_TYPE=Release
    sudo: required
    language: cpp
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        - extras-precise
        - boost-latest
        - kalakris-cmake
        packages:
        - cmake
        - lcov
        - libboost-dev
        - perl
        - gcc-6
        - g++-6
    cache:
      directories:
      - "./protobuf"
    branches:
      only:
      - coverity_scan
    before_install:
    - export SUITE=none
    - export GCOV_PATH=/usr/bin/gcov-6
    - export LCOV_PATH=$HOME/usr/bin/lcov
    - export GENHTML_PATH=$HOME/usr/bin/genhtml
    - export PREFIX=$HOME
    - export CXX="/usr/bin/g++-6" CC="/usr/bin/gcc-6";
    - bash ./ci/.travis.install-mysql-5.7.sh
    - "./ci/before_install.sh"
    install:
    - "./ci/install.sh"
    script:
    - echo "coverity scan"
    after_success:
    - echo "coverity scan success"
    
  coverity_scan:
    build_script_url: https://raw.githubusercontent.com/$TRAVIS_REPO_SLUG/$TRAVIS_BRANCH/.travis-coverity-scan-build.sh
    project:
      name: "$TRAVIS_REPO_SLUG"
    notification_email: RavenX8@users.noreply.github.com
    build_command_prepend: cov-configure --comptype gcc --compiler gcc-6 --template;
      cov-configure --comptype gcc --compiler cmake --template; mkdir build; cd build;
      cmake ..;
    build_command: make
    branch_pattern: coverity_scan
    
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/0363885535a5495e8f8f
    on_success: change
    on_failure: always
    on_start: never
  slack:
    secure: KHU2ZMzBGGtsaWF7wylutlLPAxCEZD2/NQQbmbaEpsaWSitXnO9XOLRLsLJP6QGLOgiDHHmGcRiO7wgmbsvP79zRaChs/LLfUY2F5laXgpZdL9OI/z8zygeY1iSZSNMMr0MCYf7TilRvOqTSFpB7RcuQ65G1ZGow8h6MunU5WaSyjC7REOJcSmL3IQ08Zcf8oZgdd6EqogSW1Eubcp4IhlsiQQTLdzeAQWwkfJ8DDO1gPC8bWdJCBg9hMUub5K/UQHEOY8KmH1KTOk/FedjI8wTWD+0m8SjFJq8wUs9ieQyGikZbK6F8WmjZdG0GLRWb7POxIOQjqxi2/ZRUMTHvDr5s+0BUQmKYUwkc/oUf/Bg/eYnU/LjM7prnQU08ZPGDwoh5L/alZM4eGKez3KFb4Co3e7HSI+FN9mQFKcgjnMOJIE1kaw1V+9Uj1DJemWi6voKmApJ3s8U44FduI30fpAD0FQQw8dEfF2Iug3O093KdPy0aEySOZ44a0VYD5iB7Dc129xumwOd5EAvGXHc+3/Wf0TLsskct2IlNVv6DaKkstk0YXjz7PkhkMJEAvYYi/ANQ8h/Ixh7Xnj7bcX+boBazIM6V+U6sxysQUsvWihXpxtqs+N7Z0eiRbC7s4TAMX1hVVvoERlLRVOTCl+QsRemTgt1QXV0rMl78h8xg8lg=

after_success:
  - mkdir ${PROOT}/public
  - tar -czvf ${PROOT}/public/${TRAVIS_OS_NAME}-${TRAVIS_JOB_NUMBER}-${BUILD_TYPE}.tar.gz ${PROOT}/build/bin ${PROOT}/Database

deploy:
  - provider: s3
    access_key_id: 
      secure: "UWYxD84ECFtx0u+JL+HyFgX/AzGDbAqpLeSsYzd+MkC/tkf3EHdbJTwe/x+NPpItk5QmIVYTTqLjaFoX65stNI6DYawxJmOv/mkZcSgDQm3y4yEprbdAfDSjCRduIL+uGJN1V2S6ga9HFazndSlRFWN1KbrfpJf0I7b4oGvyH4U48Z4IE1Y8/AUFXnCKAp2IHsmGdGz6fZ0P/LYuk8yAInDfOluD0golWUp9EQh/IUJ+Ke/UZy3cYaKhDRBP5kzRFrThwEOdz7/VWpSzlIOwQOZz6L+6TyaDWRBkx+RuMn9yDOEkOPjPg0AvmF8KU3O4OZmUZVKEggJrHidedd9vDMVQoKh54tKme2rMyH5qYtU1iAqoe7Z2n/PvLPM/e10NXP1/9VjBnWVJkStL/vhP9/nextdNM1jyzLNlOICrDqHNEodkvMa6DUjXjGTAi/GIgNRzkZC+FLRkVcPtq30uPHsoMNSz4/zDSkGY4EoC/zJSEwX5otQMvurS0ae9DDxLLyaVAGnerKkbn1RNcYR9If31EFQQlPZVRU3ew/EBZBgQ9l+ibIl2J3Y99/j4gB0yzEhn3tMk/dzCZ8fhlQspqCMAygNHUz2QrD09y1BgkfzpvVpXw/LwW0ddUvwreLGTfBz2KHpe26bt6WnObBM/N40s4Pa3qE77oAWCm+ysBt4="
    secret_access_key:
      secure: "rTNxFWfSexIC9pj4ZYPHLCzslkFcZC9YhoS1d8q8TeAWuDAZFzxoQfHh0NFcE3Rtx82JddZqulsL8lxbmQlebokYIgMPy7SgasV8eUUaKpIdSIm1WFUxs0qg4wLcnw+u4Wn8mkT9ZKba4PVISZl+l70JgKdldh7QMYjoGeACrNLepquIGEfnlJvcSITBXKpBfGuBTjXgtcHG6EtmrpuM+WPcOgBDKPiRDyIIrW+sRNMYZ43hccj4hj7360x9iY8V68RVGYn0sGzujtGeTym8u8vpMEYgPdY5jtsUOdlqrrqfH7pPyeAgEQIab4SmOGceSgnlcuhNPM5PLVDkbO11pEpSTrAj0wsahu/n0dDsj2B/KwM5GiNMtb2CjEs2su2SQudZEZHnN0IuNTeKFmnu9rlFpmbqf/MN2hSANsMqNFG4V4Cdl01lLGUfWkWGaBuWZ5obyWeA8aEJtDudzEpmaAI/oZu4vWVWN1gtSprm1fO8n65iGlhGf2SwaCJBESPD9TaInHWhgWbBqRefy0wx9Qe0pTh+zZHWRY+azVtUMW3B2XcCpv53qAqwcS8NTydz0Y7z5x5zbja8YYgowde9O1cXzbLKljhlOTW2mU0/tJaUXj1/4T7G4jbqAqcqr4BuTO7LO6KbJGo08gVkstNd9Ppxf5B4hmuI7fhPZKE7emg="
    bucket: osirose-builds
    skip_cleanup: true
    local-dir: ${PROOT}/public
    acl: public_read
    upload-dir: ${TRAVIS_REPO_SLUG}/${TRAVIS_BUILD_NUMBER}
    on:
      repo: RavenX8/osIROSE-new
      all_branches: true
#     branch: master
      tag: true
      
  - provider: releases
    api_key:
      secure: "BeGzqO3xstU53ChZHaEd0tx94UnOFE8mhD/47jLlBWy2MM1pxFfI9zYSfGaBAa0FBY4SjSxPyA8ChZcoHWVxSv0j59LxhI+sOyTS5Rak3UT1Nlm3WqmvRIEx5E9kuF4Z28nXQuJYPvMqdXwx7F4Qk2wRLuQHmrvllwnuEJouelR54EiAcF6h5Gk7G1j8Yvpn7kyJIJL8+a3zwEt8u4UEw8S9R4akti6EINmyYbKldVny4i8uzSas1fjeJmZlXLGvykjlcGFl4X5OEmShowRcHNjhyK7Awprbycbf7rV2es0V/UFIr+xYX/6z7sdtGiXpoBYTQksilE3IcYAt5WcvgxPnSgG12njcTHjhX+MQFW+bbYWr21OA9DQn+KfRMTI00DB3huv1KCFh5IawSjijY9j8scijMofb58vYj960yUJfoOnZeicp3raM4/eVRKCtEdk7UwWNLqqB3o1Cfug8ZohhSbUHeGUQfyCBtYWSrE6/xb5mQmOUQI54ocSUKcmvv59G58nZic0Nl29cj9aYyu1lc093gSxnQ9cCtwbNkKCHiA+Z5MGScJ5jwydylckzeQysUzOK/ISFU4O0vX48GhSBOb3D6O9K4AoVG43vBu9E895tktDuj0BQ4uvtT7fN8xDJc6vg2uAEQst0yfWJZ/qDzKJIEoFYnvbMQh0JCwA="
    file: ${PROOT}/public/${TRAVIS_OS_NAME}-${TRAVIS_JOB_NUMBER}-${BUILD_TYPE}.tar.gz
    skip_cleanup: true
    on:
      branch: master
      condition: $CXX = "/usr/bin/g++-6"
      tags: true
